# Generated by Django 5.0.3 on 2024-07-02 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lesson_is_completed_userquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='userquiz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('answer1', 'Answer 1'), ('answer2', 'Answer 2'), ('answer3', 'Answer 3'), ('answer4', 'Answer 4')], default='answer1', max_length=7),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserQuiz',
        ),
    ]
